language: go

go: 1.8.1

env:
  - TRAVIS_NODE_VERSION="7"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION

script:
  - make ftest

cache:
  directories:
    - $HOME/.pkg-cache

notifications:
  email: false
